### ISSUE TITLE
Scrollbar doesn't work on a page with more than one IR (after refresh)

### ISSUE THREAD

**Issue by ekardum** [foobarbaz-pl/apex-plugin-floating-scrollbar#13]
Hello,
on a page that has more than one interactive report,  all scrollbars stop working after region refresh. I'm struggling with that today and I really can't find a solution. Do you know what could be the problem? When i have only one dynamic action with floating scrollbar plugin, everything works well, but if I add another dynamic action (for another region), all scrollbars on that page stop working after any region refresh. 
I've tried to set event scope to dynamic and write it's Static Container manually (jquery selector) but that didn't help either.

**Comment by foobarbaz-pl** [comment]
It might be related to #10.

**Comment by ekardum** [comment]
I've tried to figure out which DOM modification is the problem when you have more than one IR on a page, but obviously that isn't the issue, something else is preventing region scrolling: scrollbar sticks normally to the bottom of IR, it just doesn't scroll it's content after refresh. Because i have also tried to set plugin initialization after refresh (not on page load so it works after dom modification), and it worked after first refresh, but it still crashes after second. If you figure something out please comment - however your plugin is very useful, thanks :)
