### ISSUE TITLE
Problem with plugin on Apex 5.0.1.00.06

### ISSUE THREAD

**Issue by Naveencheekoti** [foobarbaz-pl/apex-plugin-floating-scrollbar#14]
I tested the plug-in on Apex 5.0.1.00.0 6Interactive Report following the instructions made the settings, but the scrollbar did not appear. Tell me please, what could be the problem?

Dynamic Action
Name = DASHBOARD_PGN
Sequence = 10
Event = After Refresh
Selection Type = Region
Region = DASHBOARD

Action Properties
Action = Floating Scrollbar (Plug-In)
Region = DASHBOARD
Sequence = 10
Event = DASHBOARD_PGN
Fire When Result Is = True

It is showing following errors.
unable to load resources jquery.ba-floatingscrollbar.js,add-floating-scrollbar.js 
Uncaught ReferenceError: addFloatingScrollbar is not defined
    at Object.apex.da.initDaEventList (f?p=104:24:8988693183367::NO::::161)
    at f?p=104:24:8988693183367::NO::::188
    at HTMLDocument.<anonymous> (f?p=104:24:8988693183367::NO::::188)
    at j (jquery-2.1.3.min.js?v=5.0.1.00.06:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.3.min.js?v=5.0.1.00.06:2)
    at Function.ready (jquery-2.1.3.min.js?v=5.0.1.00.06:2)
    at HTMLDocument.I (jquery-2.1.3.min.js?v=5.0.1.00.06:2)

Help on this issue.

**Comment by foobarbaz-pl** [comment]
Hard to say, it might be a problem with ORDS or application server configuration (see #5).

**Comment by xCite1986** [comment]
try to remove the backslashes...

![26-09-2017 12-47-28](https://user-images.githubusercontent.com/10913090/30856609-2d6f9650-a2b9-11e7-8de5-81b28d5e9a51.png)
