### ISSUE TITLE
js files

### ISSUE THREAD

**Issue by vrpatel** [foobarbaz-pl/apex-plugin-floating-scrollbar#5]
I imported plug in, I see js files in Plugin 
![image](https://cloud.githubusercontent.com/assets/10655060/23311052/b27702e6-fa82-11e6-87d5-d11623f02df3.png)
but when I run Page In java console i get 
![image](https://cloud.githubusercontent.com/assets/10655060/23311143/fe01d65a-fa82-11e6-874d-a435a3f0d0fc.png)

I am running ORDS Do i need to copy files to Somewhere?

**Comment by foobarbaz-pl** [comment]
I had the same issue when APEX_PUBLIC_USER wasn't properly configured.

Please try to use some other plugin having some files bundled (e.g. [notification](http://www.oracle.com/technetwork/developer-tools/apex/notification-v-1-0-157692.zip), [timer](http://www.oracle.com/technetwork/developer-tools/apex/apex-timer-171713.zip)). Do you have the same issues?

**Comment by vrpatel** [comment]
What permission needed to be setup for APEX_PUBLIC_USER? 
As of now What I done is put js code in page javascript and it is working.
I also try to upload files to static application file and then user #APP_IMAGES# prefix for file but that is also not working.

**Comment by foobarbaz-pl** [comment]
Try [validating ORDS installation](http://docs.oracle.com/cd/E56351_01/doc.30/e56293/installing-REST-data-services.htm#AELIG7182).

**Comment by xCite1986** [comment]
for quick solution see [#14](https://github.com/foobarbaz-pl/apex-plugin-floating-scrollbar/issues/14#issuecomment-332160670)
